# .github/FUNDING.yml
custom: 
  - "https://www.youtube.com/watch?v=dQw4w9WgXcQ" # Never Gonna Give You Up
  - "https://www.youtube.com/watch?v=9jK-NcRmVcw" # The Final Countdown
  - "https://www.youtube.com/watch?v=HEXWRTEbj1I" # What Is Love
